export const SET_ONE_STUDENT_DATA = "SET_ONE_STUDENT_DATA";
export const SET_ALL_STUDENT_DATA = "SET_ALL_STUDENT_DATA";
export const SET_POST_DATA = "SET_POST_DATA";


export const LOGGED_IN_STATE = "LOGGED_IN_STATE";
export const LOGGED_OUT_STATE = "LOGGED_OUT_STATE";
export const ON_ERROR = "ON_ERROR";
